name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: [bug]
assignees:
  - Jey-Cee
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: input
    id: adapter_version
    attributes:
      label: Adapter Version
      description: What version of adapter?
      placeholder: 1.3.19
    validations:
      required: true
  - type: input
    id: deconz_version
    attributes:
      label: deConz (Phoscon) Version
      description: What version of deConz also called Phoscon?
      placeholder: 2.0.0
    validations:
      required: true
  - type: input
    id: controller_version
    attributes:
      label: JS-Controller Version
      description: What version of js-controller?
      placeholder: 3.3.15
    validations:
      required: true
  - type: input
    id: node_version
    attributes:
      label: Node JS Version
      description: What version of node js?
      placeholder: 10.0.0
    validations:
      required: true
  - type: input
    id: npm_version
    attributes:
      label: NPM Version
      description: What version of npm?
      placeholder: 6.0.0
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: On which operating system is ioBroker running?
      options:
        - Ubuntu
        - Debian
        - Windows
        - Mac OS
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
    required: false
