/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "'Please wait, searching for deConz...'": {      "en": "Please wait, searching for deConz...",            "de": "Suche deConz. Bitte warten...",                   "ru": "Подождите, ищите deConz... ",                     "pt": "Please wait, searching for deConz...",            "nl": "Please wait, searching for deConz...",            "fr": "Please wait, searching for deConz...",            "it": "Please wait, searching for deConz...",            "es": "Please wait, searching for deConz...",            "pl": "Please wait, searching for deConz..."},
    "API key": {                                     "en": "API key",                                         "de": "API Key",                                         "ru": "Ключ API",                                        "pt": "API key",                                         "nl": "API key",                                         "fr": "API key",                                         "it": "API key",                                         "es": "API key",                                         "pl": "API key"},
    "Auto setup": {                                  "en": "Auto setup",                                      "de": "Auto-Setup",                                      "ru": "Авто настройка",                                  "pt": "Auto setup",                                      "nl": "Auto setup",                                      "fr": "Auto setup",                                      "it": "Auto setup",                                      "es": "Auto setup",                                      "pl": "Auto setup"},
    "Bridge port": {                                 "en": "Bridge port",                                     "de": "Bridge-Port",                                     "ru": "Порт HUE bridge",                                 "pt": "Bridge port",                                     "nl": "Bridge port",                                     "fr": "Bridge port",                                     "it": "Bridge port",                                     "es": "Bridge port",                                     "pl": "Bridge port"},
    "Create API key": {                              "en": "Create API key",                                  "de": "Erstelle API key",                                "ru": "Создать ключ API",                                "pt": "Create API key",                                  "nl": "Create API key",                                  "fr": "Create API key",                                  "it": "Create API key",                                  "es": "Create API key",                                  "pl": "Create API key"},
    "Delete API key": {                              "en": "Delete API key",                                  "de": "Lösche API key",                                  "ru": "Удалить ключ API",                                "pt": "Delete API key",                                  "nl": "Delete API key",                                  "fr": "Delete API key",                                  "it": "Delete API key",                                  "es": "Delete API key",                                  "pl": "Delete API key"},
    "Enable adapter first": {                        "en": "Enable adapter first",                            "de": "Zu erst den Adapter Aktivieren",                  "ru": "Сначала надо активировать драйвер",               "pt": "Enable adapter first",                            "nl": "Enable adapter first",                            "fr": "Enable adapter first",                            "it": "Enable adapter first",                            "es": "Enable adapter first",                            "pl": "Enable adapter first"},
    "Instruction": {                                 "en": "Please click \"Unlock Gateway\" now! <br />You have 30 seconds.", "de": "Bitte Klicken sie jetzt auf \"Unlock Gateway\"! <br />Sie haben 30 Sekunden.", "ru": "Нажмите «Разблокировать шлюз» прямо сейчас! <br /> У вас есть 30 секунд.", "pt": "Please click \"Unlock Gateway\" now! <br />You have 30 seconds.", "nl": "Please click \"Unlock Gateway\" now! <br />You have 30 seconds.", "fr": "Please click \"Unlock Gateway\" now! <br />You have 30 seconds.", "it": "Please click \"Unlock Gateway\" now! <br />You have 30 seconds.", "es": "Please click \"Unlock Gateway\" now! <br />You have 30 seconds.", "pl": "Please click \"Unlock Gateway\" now! <br />You have 30 seconds."},
    "Ok": {                                          "en": "Ok",                                              "de": "Ok",                                              "ru": "Ok",                                              "pt": "Ok",                                              "nl": "Ok",                                              "fr": "Ok",                                              "it": "Ok",                                              "es": "Ok",                                              "pl": "Ok"},
    "Settings": {                                    "en": "Settings",                                        "de": "Einstellungen",                                   "ru": "Настройки",                                       "pt": "Settings",                                        "nl": "Settings",                                        "fr": "Settings",                                        "it": "Settings",                                        "es": "Settings",                                        "pl": "Settings"},
    "deConz Address": {                              "en": "deConz Address",                                  "de": "deConz Adresse",                                  "ru": "Адрес deConz",                                    "pt": "deConz Address",                                  "nl": "deConz Address",                                  "fr": "deConz Address",                                  "it": "deConz Address",                                  "es": "deConz Address",                                  "pl": "deConz Address"},
    "deConz adapter settings": {                     "en": "deConz adapter settings",                         "de": "deConz adapter settings",                         "ru": "Настройки драйвера deConz",                       "pt": "deConz adapter settings",                         "nl": "deConz adapter settings",                         "fr": "deConz adapter settings",                         "it": "deConz adapter settings",                         "es": "deConz adapter settings",                         "pl": "deConz adapter settings"},
    "error creating API key: ": {                    "en": "error creating API key: ",                        "de": "Fehler beim API key erstellen: ",                 "ru": "ошибка создания ключа API: ",                     "pt": "error creating API key: ",                        "nl": "error creating API key: ",                        "fr": "error creating API key: ",                        "it": "error creating API key: ",                        "es": "error creating API key: ",                        "pl": "error creating API key: "},
    "link button not pressed": {                     "en": "Please first click on \"Unlock Gateway\" in the web app", "de": "Bitte zuerst \"Unlock Gateway\" in der Web App Klicken", "ru": "Сначала нажмите «Разблокировать шлюз» в веб-приложении.", "pt": "Please first click on \"Unlock Gateway\" in the web app", "nl": "Please first click on \"Unlock Gateway\" in the web app", "fr": "Please first click on \"Unlock Gateway\" in the web app", "it": "Please first click on \"Unlock Gateway\" in the web app", "es": "Please first click on \"Unlock Gateway\" in the web app", "pl": "Please first click on \"Unlock Gateway\" in the web app"},
    "Manage deConz": {                               "en": "Manage deConz",                                   "de": "Verwalten Sie deConz",                            "ru": "Управление deConz",                              "pt": "Gerenciar DeConz",                                "nl": "Beheer deConz",                                    "fr": "Gérer deConz",                                    "it": "Gestire il deConz",                               "es": "Administrar deConz",                              "pl": "Zarządzaj deConz"},
    "Main settings": {                               "en": "Main settings",                                   "de": "Haupteinstellungen",                               "ru": "Основные настройки",                             "pt": "Configurações principais",                       "nl": "Belangrijkste instellingen",                       "fr": "Réglages principaux",                             "it": "Impostazioni principali",                         "es": "Ajustes principales",                             "pl": "Ustawienia główne"},
    "Manage Devices":{                               "en": "Manage Devices",                                  "de": "Geräte verwalten",                                 "ru": "Управление устройствами",                        "pt": "Gerenciar Dispositivos",                         "nl": "Beheer apparaten",                                 "fr": "Gérer les périphériques",                         "it": "Gestisci dispositivi",                            "es": "Administrar dispositivos",                        "pl": "Zarządzaj urządzeniami"},
    "Manage Groups":{                                "en": "Manage Groups",                                   "de": "Gruppen verwalten",                                "ru": "Управление группами",                            "pt": "Gerenciar Grupos",                               "nl": "Groepen beheren",                                  "fr": "Gérer les groupes",                               "it": "Gestisci gruppi",                                 "es": "Administrar grupos",                              "pl": "Zarządzaj grupami"},
    "deConz Version":{                               "en": "deConz Version",                                  "de": "deConz Version",                                   "ru": "Версия deConz",                                  "pt": "Versão deConz",                                  "nl": "deConz-versie",                                    "fr": "Version deConz",                                  "it": "versione deConz",                                 "es": "Versión deConz",                                  "pl": "Wersja deConz"},
    "deConz REST API Version":{                      "en": "deConz REST API Version",                         "de": "deConz REST API Version",                          "ru": "Версия API REST deConz",                         "pt": "Versão da API DEConz REST",                      "nl": "deConz REST API-versie",                           "fr": "Version de l'API REST deConz",                    "it": "Versione dell'API REST deConz",                   "es": "Versión de la API REST deConz",                   "pl": "Wersja programu REST API deConz"},
    "Create Group": {                                "en": "Create Group",                                    "de": "Gruppe erstellen",                                 "ru": "Создать группу",                                 "pt": "Criar grupo",                                    "nl": "Maak een groep",                                   "fr": "Créer un groupe",                                 "it": "Creare un gruppo",                                "es": "Crea un grupo",                                   "pl": "Stworzyć grupę"},
    "Open Network": {
        "en": "Open Network",
        "de": "Netzwerk öffnen",
        "ru": "Открытая сеть",
        "pt": "Rede Aberta",
        "nl": "Open netwerk",
        "fr": "Réseau ouvert",
        "it": "Apri la rete",
        "es": "Red abierta",
        "pl": "Otwórz sieć"
    },
    "Duration": {
        "en": "Duration",
        "de": "Dauer",
        "ru": "продолжительность",
        "pt": "Duração",
        "nl": "Looptijd",
        "fr": "Durée",
        "it": "Durata",
        "es": "Duración",
        "pl": "Trwanie"
    },
    "Name": {
        "en": "Name",
        "de": "Name",
        "ru": "имя",
        "pt": "Nome",
        "nl": "Naam",
        "fr": "prénom",
        "it": "Nome",
        "es": "Nombre",
        "pl": "Nazwa"
    },
    "Manufacturer": {
        "en": "Manufacturer",
        "de": "Hersteller",
        "ru": "производитель",
        "pt": "Fabricante",
        "nl": "Fabrikant",
        "fr": "Fabricant",
        "it": "fabbricante",
        "es": "Fabricante",
        "pl": "Producent"
    },
    "Model ID": {
        "en": "Model ID",
        "de": "Modell-ID",
        "ru": "ID модели",
        "pt": "ID do modelo",
        "nl": "Model ID",
        "fr": "ID du modèle",
        "it": "ID modello",
        "es": "ID de modelo",
        "pl": "ID modelu"
    },
    "Type": {
        "en": "Type",
        "de": "Art",
        "ru": "Тип",
        "pt": "Tipo",
        "nl": "Type",
        "fr": "Type",
        "it": "genere",
        "es": "Tipo",
        "pl": "Rodzaj"
    },
    "Devices (ID of Device)": {
        "en": "Devices (ID of Device)",
        "de": "Geräte (ID des Geräts)",
        "ru": "Устройства (ID устройства)",
        "pt": "Dispositivos (ID do dispositivo)",
        "nl": "Apparaten (ID van apparaat)",
        "fr": "Périphériques (ID du périphérique)",
        "it": "Dispositivi (ID del dispositivo)",
        "es": "Dispositivos (ID del dispositivo)",
        "pl": "Urządzenia (identyfikator urządzenia)"
    },
    "Lights (ID of Light)": {
        "en": "Lights (ID of Light)",
        "de": "Lampen (ID der Lampe)",
        "ru": "Свет (ID света)",
        "pt": "Luzes (ID da Luz)",
        "nl": "Lichten (ID van licht)",
        "fr": "Lumières (ID de la lumière)",
        "it": "Luci (ID della luce)",
        "es": "Luces (ID de luz)",
        "pl": "Światła (ID światła)"
    },
    "Name of the new group:": {
        "en": "Name of the new group:",
        "de": "Name der neuen Gruppe:",
        "ru": "Название новой группы:",
        "pt": "Nome do novo grupo:",
        "nl": "Naam van de nieuwe groep:",
        "fr": "Nom du nouveau groupe:",
        "it": "Nome del nuovo gruppo:",
        "es": "Nombre del nuevo grupo:",
        "pl": "Nazwa nowej grupy:"
    }
};